verbose: false
instrumentation:
  root: .
  extensions:
    - .js
  default-excludes: true
  excludes: ["benchmark/*.js"]
  embed-source: false
  variable: __coverage__
  compact: true
  preserve-comments: true
  complete-copy: false
  save-baseline: false
  baseline-file: ./coverage/coverage-baseline.json
  include-all-sources: true
  include-pid: false
  es-modules: true
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
  watermarks:
    statements: [80, 95]
    lines: [80, 95]
    functions: [80, 95]
    branches: [80, 95]
hooks:
  hook-run-in-context: false
  post-require-hook: null
  handle-sigint: false

check:
  global:
    statements: 96
    lines: 96
    branches: 85
    functions: 100
    excludes: []
